{{wrap with="layout.phtml"}}
{{into slot="meta"}}
<meta property="og:type" content="{$#facebook_app_namespace}:coin"/>
<meta property="og:title" content="TYCoin"/>
<meta property="og:url" content="{$#host_url}pages/{$#transaction.id}/transaction"/>
<meta property="tycoins:recipient" content="http://graph.facebook.com/{$#recipient_fb_uid}"/>
<meta property="og:image" content="http://thx.onedayofmine.com/images/big-coin.jpg"/>
{{/into}}
{{into slot="content"}}
<h1>Transaction #{$#transaction.id}</h1>
<ul>
    <li>id: {$#transaction.id}</li>
    <li>user_id: {$#transaction.user_id}</li>
    <li>description: {$#transaction.message}</li>
</ul>
{{/into}}
{{/wrap}}
