{{wrap with="layout.phtml"}}
{{into slot="meta"}}
  <meta property="og:type" content="{$#facebook_app_namespace}:transaction"/>
  <meta property="og:title" content="Thank's"/>
  <meta property="og:url" content="{$#host_url}pages/{$#transaction.id}/transaction"/>
  <meta property="tycoins:to" content="{$#recipient_fb_uid}"/>
  <meta property="tycoins:coin" content="http://thx.onedayofmine.com/og/coin_{$#transaction.coins_type}.html"/>
  <meta property="og:image" content="http://thx.onedayofmine.com/images/{$#transaction.coins_type}-coin.jpg"/>
{{/into}}
{{into slot="content"}}
  <h1>Transaction #{$#transaction.id}</h1>
  <ul>
    <li>id: {$#transaction.id}</li>
    <li>user_id: {$#transaction.user_id}</li>
    <li>description: {$#transaction.message}</li>
  </ul>
{{/into}}
{{/wrap}}
